// AUTO-GENERATED by setup-showcase. Do not edit by hand.
export type GalleryItem = { src: string; thumb: string; label: string };
export type StoryItem = { src: string; thumb: string; title: string; desc: string };

export const GALLERY: GalleryItem[] = [
  {
    "src": "/showcase/gallery/g001.webp",
    "thumb": "/showcase/gallery/g001@t.webp",
    "label": "Infeed pick"
  },
  {
    "src": "/showcase/gallery/g002.webp",
    "thumb": "/showcase/gallery/g002@t.webp",
    "label": "Mixed-SKU build"
  },
  {
    "src": "/showcase/gallery/g003.webp",
    "thumb": "/showcase/gallery/g003@t.webp",
    "label": "Guarded line-end"
  },
  {
    "src": "/showcase/gallery/g004.webp",
    "thumb": "/showcase/gallery/g004@t.webp",
    "label": "Dual-station changeover"
  },
  {
    "src": "/showcase/gallery/g005.webp",
    "thumb": "/showcase/gallery/g005@t.webp",
    "label": "Lights-out shift"
  },
  {
    "src": "/showcase/gallery/g006.webp",
    "thumb": "/showcase/gallery/g006@t.webp",
    "label": "Layer close-up"
  },
  {
    "src": "/showcase/gallery/g007.webp",
    "thumb": "/showcase/gallery/g007@t.webp",
    "label": "Twin-pallet cell"
  },
  {
    "src": "/showcase/gallery/g008.webp",
    "thumb": "/showcase/gallery/g008@t.webp",
    "label": "High-density top-off"
  },
  {
    "src": "/showcase/gallery/g009.webp",
    "thumb": "/showcase/gallery/g009@t.webp",
    "label": "Sanitary cell"
  },
  {
    "src": "/showcase/gallery/g010.webp",
    "thumb": "/showcase/gallery/g010@t.webp",
    "label": "Full-cell overview"
  },
  {
    "src": "/showcase/gallery/g011.webp",
    "thumb": "/showcase/gallery/g011@t.webp",
    "label": "Infeed pick"
  },
  {
    "src": "/showcase/gallery/g012.webp",
    "thumb": "/showcase/gallery/g012@t.webp",
    "label": "Mixed-SKU build"
  },
  {
    "src": "/showcase/gallery/g013.webp",
    "thumb": "/showcase/gallery/g013@t.webp",
    "label": "Guarded line-end"
  },
  {
    "src": "/showcase/gallery/g014.webp",
    "thumb": "/showcase/gallery/g014@t.webp",
    "label": "Dual-station changeover"
  },
  {
    "src": "/showcase/gallery/g015.webp",
    "thumb": "/showcase/gallery/g015@t.webp",
    "label": "Lights-out shift"
  },
  {
    "src": "/showcase/gallery/g016.webp",
    "thumb": "/showcase/gallery/g016@t.webp",
    "label": "Layer close-up"
  },
  {
    "src": "/showcase/gallery/g017.webp",
    "thumb": "/showcase/gallery/g017@t.webp",
    "label": "Twin-pallet cell"
  },
  {
    "src": "/showcase/gallery/g018.webp",
    "thumb": "/showcase/gallery/g018@t.webp",
    "label": "High-density top-off"
  },
  {
    "src": "/showcase/gallery/g019.webp",
    "thumb": "/showcase/gallery/g019@t.webp",
    "label": "Sanitary cell"
  },
  {
    "src": "/showcase/gallery/g020.webp",
    "thumb": "/showcase/gallery/g020@t.webp",
    "label": "Full-cell overview"
  },
  {
    "src": "/showcase/gallery/g021.webp",
    "thumb": "/showcase/gallery/g021@t.webp",
    "label": "Infeed pick"
  },
  {
    "src": "/showcase/gallery/g022.webp",
    "thumb": "/showcase/gallery/g022@t.webp",
    "label": "Mixed-SKU build"
  },
  {
    "src": "/showcase/gallery/g023.webp",
    "thumb": "/showcase/gallery/g023@t.webp",
    "label": "Guarded line-end"
  },
  {
    "src": "/showcase/gallery/g024.webp",
    "thumb": "/showcase/gallery/g024@t.webp",
    "label": "Dual-station changeover"
  },
  {
    "src": "/showcase/gallery/g025.webp",
    "thumb": "/showcase/gallery/g025@t.webp",
    "label": "Lights-out shift"
  },
  {
    "src": "/showcase/gallery/g026.webp",
    "thumb": "/showcase/gallery/g026@t.webp",
    "label": "Layer close-up"
  },
  {
    "src": "/showcase/gallery/g027.webp",
    "thumb": "/showcase/gallery/g027@t.webp",
    "label": "Twin-pallet cell"
  },
  {
    "src": "/showcase/gallery/g028.webp",
    "thumb": "/showcase/gallery/g028@t.webp",
    "label": "High-density top-off"
  },
  {
    "src": "/showcase/gallery/g029.webp",
    "thumb": "/showcase/gallery/g029@t.webp",
    "label": "Sanitary cell"
  },
  {
    "src": "/showcase/gallery/g030.webp",
    "thumb": "/showcase/gallery/g030@t.webp",
    "label": "Full-cell overview"
  },
  {
    "src": "/showcase/gallery/g031.webp",
    "thumb": "/showcase/gallery/g031@t.webp",
    "label": "Infeed pick"
  },
  {
    "src": "/showcase/gallery/g032.webp",
    "thumb": "/showcase/gallery/g032@t.webp",
    "label": "Mixed-SKU build"
  },
  {
    "src": "/showcase/gallery/g033.webp",
    "thumb": "/showcase/gallery/g033@t.webp",
    "label": "Guarded line-end"
  },
  {
    "src": "/showcase/gallery/g034.webp",
    "thumb": "/showcase/gallery/g034@t.webp",
    "label": "Dual-station changeover"
  },
  {
    "src": "/showcase/gallery/g035.webp",
    "thumb": "/showcase/gallery/g035@t.webp",
    "label": "Lights-out shift"
  },
  {
    "src": "/showcase/gallery/g036.webp",
    "thumb": "/showcase/gallery/g036@t.webp",
    "label": "Layer close-up"
  },
  {
    "src": "/showcase/gallery/g037.webp",
    "thumb": "/showcase/gallery/g037@t.webp",
    "label": "Twin-pallet cell"
  },
  {
    "src": "/showcase/gallery/g038.webp",
    "thumb": "/showcase/gallery/g038@t.webp",
    "label": "High-density top-off"
  },
  {
    "src": "/showcase/gallery/g039.webp",
    "thumb": "/showcase/gallery/g039@t.webp",
    "label": "Sanitary cell"
  },
  {
    "src": "/showcase/gallery/g040.webp",
    "thumb": "/showcase/gallery/g040@t.webp",
    "label": "Full-cell overview"
  },
  {
    "src": "/showcase/gallery/g041.webp",
    "thumb": "/showcase/gallery/g041@t.webp",
    "label": "Infeed pick"
  },
  {
    "src": "/showcase/gallery/g042.webp",
    "thumb": "/showcase/gallery/g042@t.webp",
    "label": "Mixed-SKU build"
  },
  {
    "src": "/showcase/gallery/g043.webp",
    "thumb": "/showcase/gallery/g043@t.webp",
    "label": "Guarded line-end"
  },
  {
    "src": "/showcase/gallery/g044.webp",
    "thumb": "/showcase/gallery/g044@t.webp",
    "label": "Dual-station changeover"
  },
  {
    "src": "/showcase/gallery/g045.webp",
    "thumb": "/showcase/gallery/g045@t.webp",
    "label": "Lights-out shift"
  },
  {
    "src": "/showcase/gallery/g046.webp",
    "thumb": "/showcase/gallery/g046@t.webp",
    "label": "Layer close-up"
  },
  {
    "src": "/showcase/gallery/g047.webp",
    "thumb": "/showcase/gallery/g047@t.webp",
    "label": "Twin-pallet cell"
  },
  {
    "src": "/showcase/gallery/g048.webp",
    "thumb": "/showcase/gallery/g048@t.webp",
    "label": "High-density top-off"
  },
  {
    "src": "/showcase/gallery/g049.webp",
    "thumb": "/showcase/gallery/g049@t.webp",
    "label": "Sanitary cell"
  },
  {
    "src": "/showcase/gallery/g050.webp",
    "thumb": "/showcase/gallery/g050@t.webp",
    "label": "Full-cell overview"
  },
  {
    "src": "/showcase/gallery/g051.webp",
    "thumb": "/showcase/gallery/g051@t.webp",
    "label": "Infeed pick"
  },
  {
    "src": "/showcase/gallery/g052.webp",
    "thumb": "/showcase/gallery/g052@t.webp",
    "label": "Mixed-SKU build"
  },
  {
    "src": "/showcase/gallery/g053.webp",
    "thumb": "/showcase/gallery/g053@t.webp",
    "label": "Guarded line-end"
  },
  {
    "src": "/showcase/gallery/g054.webp",
    "thumb": "/showcase/gallery/g054@t.webp",
    "label": "Dual-station changeover"
  },
  {
    "src": "/showcase/gallery/g055.webp",
    "thumb": "/showcase/gallery/g055@t.webp",
    "label": "Lights-out shift"
  },
  {
    "src": "/showcase/gallery/g056.webp",
    "thumb": "/showcase/gallery/g056@t.webp",
    "label": "Layer close-up"
  },
  {
    "src": "/showcase/gallery/g057.webp",
    "thumb": "/showcase/gallery/g057@t.webp",
    "label": "Twin-pallet cell"
  },
  {
    "src": "/showcase/gallery/g058.webp",
    "thumb": "/showcase/gallery/g058@t.webp",
    "label": "High-density top-off"
  },
  {
    "src": "/showcase/gallery/g059.webp",
    "thumb": "/showcase/gallery/g059@t.webp",
    "label": "Sanitary cell"
  },
  {
    "src": "/showcase/gallery/g060.webp",
    "thumb": "/showcase/gallery/g060@t.webp",
    "label": "Full-cell overview"
  },
  {
    "src": "/showcase/gallery/g061.webp",
    "thumb": "/showcase/gallery/g061@t.webp",
    "label": "Infeed pick"
  },
  {
    "src": "/showcase/gallery/g062.webp",
    "thumb": "/showcase/gallery/g062@t.webp",
    "label": "Mixed-SKU build"
  },
  {
    "src": "/showcase/gallery/g063.webp",
    "thumb": "/showcase/gallery/g063@t.webp",
    "label": "Guarded line-end"
  },
  {
    "src": "/showcase/gallery/g064.webp",
    "thumb": "/showcase/gallery/g064@t.webp",
    "label": "Dual-station changeover"
  },
  {
    "src": "/showcase/gallery/g065.webp",
    "thumb": "/showcase/gallery/g065@t.webp",
    "label": "Lights-out shift"
  },
  {
    "src": "/showcase/gallery/g066.webp",
    "thumb": "/showcase/gallery/g066@t.webp",
    "label": "Layer close-up"
  },
  {
    "src": "/showcase/gallery/g067.webp",
    "thumb": "/showcase/gallery/g067@t.webp",
    "label": "Twin-pallet cell"
  },
  {
    "src": "/showcase/gallery/g068.webp",
    "thumb": "/showcase/gallery/g068@t.webp",
    "label": "High-density top-off"
  },
  {
    "src": "/showcase/gallery/g069.webp",
    "thumb": "/showcase/gallery/g069@t.webp",
    "label": "Sanitary cell"
  },
  {
    "src": "/showcase/gallery/g070.webp",
    "thumb": "/showcase/gallery/g070@t.webp",
    "label": "Full-cell overview"
  },
  {
    "src": "/showcase/gallery/g071.webp",
    "thumb": "/showcase/gallery/g071@t.webp",
    "label": "Infeed pick"
  },
  {
    "src": "/showcase/gallery/g072.webp",
    "thumb": "/showcase/gallery/g072@t.webp",
    "label": "Mixed-SKU build"
  },
  {
    "src": "/showcase/gallery/g073.webp",
    "thumb": "/showcase/gallery/g073@t.webp",
    "label": "Guarded line-end"
  },
  {
    "src": "/showcase/gallery/g074.webp",
    "thumb": "/showcase/gallery/g074@t.webp",
    "label": "Dual-station changeover"
  },
  {
    "src": "/showcase/gallery/g075.webp",
    "thumb": "/showcase/gallery/g075@t.webp",
    "label": "Lights-out shift"
  },
  {
    "src": "/showcase/gallery/g076.webp",
    "thumb": "/showcase/gallery/g076@t.webp",
    "label": "Layer close-up"
  },
  {
    "src": "/showcase/gallery/g077.webp",
    "thumb": "/showcase/gallery/g077@t.webp",
    "label": "Twin-pallet cell"
  },
  {
    "src": "/showcase/gallery/g078.webp",
    "thumb": "/showcase/gallery/g078@t.webp",
    "label": "High-density top-off"
  },
  {
    "src": "/showcase/gallery/g079.webp",
    "thumb": "/showcase/gallery/g079@t.webp",
    "label": "Sanitary cell"
  },
  {
    "src": "/showcase/gallery/g080.webp",
    "thumb": "/showcase/gallery/g080@t.webp",
    "label": "Full-cell overview"
  }
];

export const FEATURE_STORY: StoryItem[] = [
  {
    "src": "/showcase/story/01.webp",
    "thumb": "/showcase/story/01@t.webp",
    "title": "End-of-Line Cell",
    "desc": "A complete palletizing cell \u2014 one software layer driving arm, gripper, vision and safety."
  },
  {
    "src": "/showcase/story/02.webp",
    "thumb": "/showcase/story/02@t.webp",
    "title": "Precision AI Gripper",
    "desc": "Vision-guided tooling that seals, lifts and seats each case within the confidence gate."
  },
  {
    "src": "/showcase/story/03.webp",
    "thumb": "/showcase/story/03@t.webp",
    "title": "AI Mixed-SKU Pallet",
    "desc": "Live optimization packs mixed cases into a dense, physics-validated stack."
  },
  {
    "src": "/showcase/story/04.webp",
    "thumb": "/showcase/story/04@t.webp",
    "title": "One Codebase, Any Robot",
    "desc": "The same engine drives any supported arm through a sub-100-line driver."
  },
  {
    "src": "/showcase/story/05.webp",
    "thumb": "/showcase/story/05@t.webp",
    "title": "Global Fleet Command",
    "desc": "Every cell, every site \u2014 monitored and orchestrated from one control plane."
  },
  {
    "src": "/showcase/story/06.webp",
    "thumb": "/showcase/story/06@t.webp",
    "title": "Safety-First Collaboration",
    "desc": "Guarding, light curtains and a 2.5 s watchdog keep people and product safe."
  },
  {
    "src": "/showcase/story/07.webp",
    "thumb": "/showcase/story/07@t.webp",
    "title": "High Throughput",
    "desc": "Sustained ~120 cases/hr per cell without sacrificing stack stability."
  },
  {
    "src": "/showcase/story/08.webp",
    "thumb": "/showcase/story/08@t.webp",
    "title": "RobotInterface < 100 Lines",
    "desc": "Onboard a new arm by implementing one tiny, well-documented interface."
  },
  {
    "src": "/showcase/story/09.webp",
    "thumb": "/showcase/story/09@t.webp",
    "title": "Food & Beverage Sanitary",
    "desc": "Washdown-rated tooling and per-case traceability for hygiene-critical lines."
  },
  {
    "src": "/showcase/story/10.webp",
    "thumb": "/showcase/story/10@t.webp",
    "title": "E-commerce Mixed-SKU",
    "desc": "Extreme SKU variety, peak-season ready, maximum cases per pallet."
  },
  {
    "src": "/showcase/story/11.webp",
    "thumb": "/showcase/story/11@t.webp",
    "title": "Digital Twin, Sim-to-Real",
    "desc": "Validate patterns in simulation, then run the identical plan on hardware."
  },
  {
    "src": "/showcase/story/12.webp",
    "thumb": "/showcase/story/12@t.webp",
    "title": "Scale to Global Fleets",
    "desc": "From a single pilot cell to a worldwide, audited deployment."
  }
];
