"use client";

import React, { useState } from 'react';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import { Upload, Play, Download, CheckCircle, AlertTriangle, Zap } from 'lucide-react';
import { toast } from 'sonner';
import PalletVisualizer3D from '@/components/PalletVisualizer3D';
import ROICalculator from '@/components/ROICalculator';
import { planFromBoxes } from '@/lib/palletizer/optimizer';
import { parseSkuCsv, BEVERAGE_ORDER } from '@/lib/palletizer/sampleData';
import type { WebPlan, BoxSpec } from '@/lib/palletizer/types';

type PalletPlan = WebPlan;

export default function LiveOptimizerDemo() {
  const [plan, setPlan] = useState<PalletPlan | null>(null);
  const [isOptimizing, setIsOptimizing] = useState(false);
  const [csvData, setCsvData] = useState<any[]>([]);
  const [fileName, setFileName] = useState('');

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      const boxes = parseSkuCsv(String(event.target?.result ?? ''));
      setCsvData(boxes);
      setFileName(file.name);
      toast.success(`${boxes.length} SKUs loaded from ${file.name}`);
    };
    reader.readAsText(file);
  };

  // Runs the REAL optimizer: a function-for-function TypeScript port of
  // palletizer_full/optimizer.py. Placements, density, uplift, and stability
  // are all derived from the computed geometry — nothing is simulated.
  const runOptimizer = async () => {
    setIsOptimizing(true);
    // brief yield so the button state paints; the engine itself is < 5 ms
    await new Promise((resolve) => setTimeout(resolve, 350));

    const skusToUse: BoxSpec[] = csvData.length > 0 ? (csvData as BoxSpec[]) : BEVERAGE_ORDER;
    const plan = planFromBoxes(skusToUse, {}, undefined, `plan_demo_${Date.now()}`);

    setPlan(plan);
    setIsOptimizing(false);
    toast.success('Optimization complete — plan derived from geometry.', {
      description: `${plan.metrics.num_boxes} boxes • ${(plan.metrics.volume_density * 100).toFixed(1)}% density • stability ${plan.metrics.stability_score.toFixed(2)}`,
    });
  };

  const downloadPlan = (format: 'json' | 'urscript') => {
    if (!plan) return;

    let content = '';
    let filename = '';

    if (format === 'json') {
      content = JSON.stringify(plan, null, 2);
      filename = `${plan.plan_id}.json`;
    } else {
      content = `def palletize_${plan.plan_id}():\n    # Generated by Palletizer Live Optimizer v0.2\n`;
      plan.boxes.forEach((p, i) => {
        content += `    # ${i+1}. ${p.sku_id} @ Layer ${p.layer}\n`;
        content += `    place_pose = p[${(p.x_mm/1000).toFixed(3)}, ${(p.y_mm/1000).toFixed(3)}, ${(((p.z_mm + p.height_mm)/1000) + 0.08).toFixed(3)}, 0, 3.1416, ${ (p.rot_deg * Math.PI / 180).toFixed(3) }]\n`;
      });
      filename = `${plan.plan_id}.urscript`;
    }

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    
    toast.success(`${format.toUpperCase()} downloaded`, { description: filename });
  };

  return (
    <div className="min-h-screen bg-[#0f172a] pt-20 pb-16">
      <div className="max-w-7xl mx-auto px-6">
        {/* Header */}
        <div className="flex items-end justify-between mb-8">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <div className="px-3 py-1 bg-primary/10 text-primary text-xs tracking-[2px] rounded">PRODUCTION DEMO</div>
              <div className="text-xs text-white/50">POWERED BY SMARTPALLETOPTIMIZER v0.2 • INTEGRATES WITH GITHUB REPO</div>
            </div>
            <h1 className="text-4xl md:text-6xl font-semibold tracking-tighter">Live Pallet Optimizer</h1>
            <p className="text-lg sm:text-2xl text-white/70 mt-1">Upload real SKU data. Get validated plans. See the ROI.</p>
          </div>
          <div className="hidden md:flex gap-3">
            <Link href="/demos"
                  className="text-sm px-5 py-2 bg-emerald-600 hover:bg-emerald-500 rounded-2xl font-medium transition">
              Interactive Demo Suite →
            </Link>
            <Link href="https://github.com/iceccarelli/palletizer" target="_blank"
                  className="text-sm px-5 py-2 border border-white/20 rounded-2xl hover:bg-white/5">
              View Full Python Source →
            </Link>
          </div>
        </div>

        <div className="grid lg:grid-cols-12 gap-6">
          {/* Control Panel */}
          <div className="lg:col-span-5 space-y-6">
            <div className="glass p-8 rounded-3xl border border-white/10">
              <h3 className="font-semibold text-xl mb-4 flex items-center gap-2">
                <Upload className="w-5 h-5" /> 1. Upload Your SKU Data (CSV)
              </h3>
              <p className="text-sm text-white/60 mb-4">Real customer data from WMS/ERP. Columns: sku_id, length_mm, width_mm, height_mm, weight_kg</p>
              
              <label className="flex flex-col items-center justify-center border-2 border-dashed border-white/30 hover:border-primary/60 rounded-2xl py-9 cursor-pointer transition">
                <Upload className="w-8 h-8 mb-3 text-white/60" />
                <span className="font-medium">Drop CSV or click to upload</span>
                <span className="text-xs text-white/50 mt-1">or run the sample 42-box order</span>
                <input type="file" accept=".csv" onChange={handleFileUpload} className="hidden" />
              </label>
              
              {fileName && <div className="mt-3 text-emerald-400 text-sm flex items-center gap-2"><CheckCircle className="w-4 h-4" /> {fileName} loaded ({csvData.length} SKUs)</div>}

              <button 
                onClick={runOptimizer}
                disabled={isOptimizing}
                className="mt-6 w-full flex items-center justify-center gap-3 py-4 bg-primary hover:bg-primary/90 disabled:bg-primary/60 text-lg font-semibold rounded-2xl transition active:scale-[0.985]"
              >
                {isOptimizing ? (
                  <>Optimizing with physics engine... <div className="w-4 h-4 border-2 border-white/30 border-t-white animate-spin rounded-full" /></>
                ) : (
                  <>Run Live Optimization <Play className="w-5 h-5" /></>
                )}
              </button>
              <p className="text-center text-[10px] text-white/50 mt-3 tracking-widest">USES REAL-TIME STABILITY SCORING • NO HARDCODED PATTERNS</p>
            </div>

            {/* Quick Sample CTA */}
            {!plan && (
              <button onClick={runOptimizer} className="w-full py-3 text-sm border border-white/20 hover:bg-white/5 rounded-2xl flex items-center justify-center gap-2">
                <Zap className="w-4 h-4" /> Use Sample Beverage SKUs (Instant Demo)
              </button>
            )}
          </div>

          {/* Results Dashboard */}
          <div className="lg:col-span-7">
            <AnimatePresence mode="wait">
              {!plan ? (
                <div className="glass h-[520px] rounded-3xl border border-white/10 flex flex-col items-center justify-center text-center p-12">
                  <div className="w-20 h-20 rounded-2xl bg-white/5 flex items-center justify-center mb-6">
                    <Play className="w-10 h-10 text-primary/70" />
                  </div>
                  <h3 className="text-3xl font-semibold tracking-tight mb-3">Your optimized pallet appears here</h3>
                  <p className="max-w-xs text-white/60">Upload CSV or run sample → Get density, stability score, 3D visualization, and exportable robot code.</p>
                </div>
              ) : (
                <motion.div 
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="space-y-6"
                >
                  {/* Metrics Bar */}
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    {[
                      { label: "Density", value: `${(plan.metrics.volume_density * 100).toFixed(1)}%`, sub: `${plan.metrics.density_uplift_pct >= 0 ? "+" : ""}${plan.metrics.density_uplift_pct}% vs naive stacking` },
                      { label: "Stability", value: plan.metrics.stability_score.toFixed(2), sub: "Support × CoM model" },
                      { label: "Boxes / Layers", value: `${plan.metrics.num_boxes} / ${plan.metrics.num_layers}`, sub: `${plan.metrics.unique_skus} SKUs` },
                      { label: "Build Time", value: `${plan.metrics.est_build_time_min} min`, sub: "Est. robot cycle" },
                    ].map((m, i) => (
                      <div key={i} className="glass p-5 rounded-2xl border border-white/10">
                        <div className="text-xs text-white/60 mb-1">{m.label}</div>
                        <div className="text-4xl font-mono font-semibold tracking-tighter">{m.value}</div>
                        <div className="text-emerald-400 text-xs mt-0.5">{m.sub}</div>
                      </div>
                    ))}
                  </div>

                  {/* Validation */}
                  <div className={`p-5 rounded-2xl border flex items-start gap-4 ${plan.validation_report.is_valid ? 'border-emerald-500/40 bg-emerald-950/30' : 'border-amber-500/40 bg-amber-950/20'}`}>
                    {plan.validation_report.is_valid ? <CheckCircle className="w-6 h-6 text-emerald-400 mt-0.5" /> : <AlertTriangle className="w-6 h-6 text-amber-400 mt-0.5" />}
                    <div>
                      <div className="font-semibold">{plan.validation_report.is_valid ? "PLAN VALIDATED" : "REVIEW RECOMMENDED"}</div>
                      <div className="text-sm text-white/70 mt-0.5">{plan.validation_report.recommendations.length > 0 ? plan.validation_report.recommendations[0] : "Ready for production deployment or further refinement."}</div>
                    </div>
                  </div>

                  {/* 3D VISUALIZER - The Billion Dollar Moment */}
                  <div className="glass rounded-3xl p-2 border border-white/10">
                    <div className="flex items-center justify-between px-6 pt-4 pb-2">
                      <div>
                        <div className="font-semibold">3D Pallet Visualization</div>
                        <div className="text-xs text-white/50">Interactive • Orbit • Hover for details • Powered by Three.js</div>
                      </div>
                      <div className="text-xs px-3 py-1 bg-white/10 rounded">PLAN {plan.plan_id.split('_').pop()}</div>
                    </div>
                    <PalletVisualizer3D plan={plan} />
                  </div>

                  {/* Actions */}
                  <div className="flex flex-wrap gap-3">
                    <button onClick={() => downloadPlan('json')} className="flex-1 flex items-center justify-center gap-2 py-3.5 bg-white/10 hover:bg-white/15 rounded-2xl font-medium transition">
                      <Download className="w-4 h-4" /> Download Plan JSON
                    </button>
                    <button onClick={() => downloadPlan('urscript')} className="flex-1 flex items-center justify-center gap-2 py-3.5 bg-white/10 hover:bg-white/15 rounded-2xl font-medium transition">
                      <Download className="w-4 h-4" /> Download URScript (Robot)
                    </button>
                    <button onClick={() => { setPlan(null); setCsvData([]); setFileName(''); }} className="px-8 py-3.5 border border-white/20 hover:bg-white/5 rounded-2xl text-sm">
                      New Optimization
                    </button>
                  </div>

                  {/* ROI Quick View */}
                  <ROICalculator plan={plan} />

                  {/* The hook into the game loop */}
                  <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}
                    className="p-6 rounded-3xl border border-emerald-500/30 bg-gradient-to-r from-emerald-950/40 to-transparent flex items-center justify-between flex-wrap gap-4">
                    <div>
                      <div className="font-semibold text-lg">Think you can beat this plan? 🏆</div>
                      <div className="text-sm text-white/60 mt-0.5">
                        Drag the boxes yourself in the Interactive Suite — the same math scores your layout against the
                        engine's, live. Break it, fix it, beat it.
                      </div>
                    </div>
                    <Link href="/demos" className="px-6 py-3 bg-emerald-600 hover:bg-emerald-500 rounded-2xl font-semibold whitespace-nowrap transition">
                      Enter the Demo Suite →
                    </Link>
                  </motion.div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>

        <div className="mt-12 text-center text-xs text-white/40 max-w-md mx-auto">
          This page runs a function-for-function TypeScript port of the open-source Python optimizer — identical placements, identical metrics.<br />
          Full backend + API + multi-cell orchestration available in Enterprise.
        </div>
      </div>
    </div>
  );
}
