// Shared export helpers. The URScript format is byte-identical to the one the
// original /demo page produced, so nothing downstream breaks.

import { Placement, WebPlan } from './types';

export function urscriptFor(planId: string, boxes: Placement[]): string {
  let content = `def palletize_${planId}():\n    # Generated by Palletizer Live Optimizer v0.2\n`;
  boxes.forEach((p, i) => {
    content += `    # ${i + 1}. ${p.sku_id} @ Layer ${p.layer}\n`;
    content += `    place_pose = p[${(p.x_mm / 1000).toFixed(3)}, ${(p.y_mm / 1000).toFixed(3)}, ${(
      (p.z_mm + p.height_mm) / 1000 +
      0.08
    ).toFixed(3)}, 0, 3.1416, ${((p.rot_deg * Math.PI) / 180).toFixed(3)}]\n`;
  });
  return content;
}

export function downloadText(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadPlanJson(plan: WebPlan) {
  downloadText(JSON.stringify(plan, null, 2), `${plan.plan_id}.json`);
}

export function downloadUrscript(plan: WebPlan) {
  downloadText(urscriptFor(plan.plan_id, plan.boxes), `${plan.plan_id}.urscript`);
}
